### ISSUE TITLE
Do i need for racechono, harrys Laptimer etc. Taskscheduler?

### ISSUE THREAD

**Issue by R1Snake** [renatobo/bonogps#27]
Hi,

i am using an esp32 with NEO 8M and without a battery.

The ESP is powered via ignition power of my bike so I don't need deepsleep, battery information etc.

Do I need the Taskscheduler for Racechrono or another racing app? If not I would disable this functionality.

**Comment by renatobo** [comment]
Hi R1Snake!

Please note that a M8N might be limited to 5Hz updates unless you enable only 1 satellite constellation (which is essentially GPS only) then you can get to 10Hz (see the [hardware/GPS](https://github.com/renatobo/bonogps/tree/main/hardware/GPS#q-m8n-m8q-m8u--which-one) section)

**A note on battery support**
Battery support is optional and activated (and compiled in the code) only when the macro `SHOWBATTERY` is defined (right now I only tested on the Lolin D32 Pro).
Not requiring a battery makes for a much easier hardware configuration indeed: be aware of one limitation which is tied to the cold start of the GPS unit at the beginning of your day when it requires some time (even minutes) to find satellites.

**TaskScheduler**

TaskScheduler is optional and it supports

1. status LED blinking: off, slow blink, fast blink to show WiFi status
2. periodic polling GSA and GSV information. These are not actually required for GPS positioning
3. power saving
4. battery status notifications
2. disabling OTA updates after some configured time

Number 2 above is the only one that changes data sent to your app of choice, the other are helper functions that don't impact base GPS functionality.

You can undefine the macro `TASK_SCHEDULER` to remove it.

A couple of questions

1. Is your goal simpler code, smaller binary, or else?
2. what apps are you using and which connection method (BLE,BTSPP,WiFi) ?
